### ISSUE TITLE
Could not fetch the login URL from iTunes Connect

### ISSUE THREAD

**Issue by aaronwardle** [fastlane/watchbuild#5]
Hi, 

I have just tried to use watchbuild but it looks like the recent update to iTunesConnect, as soon as I run it I am getting this error. 

```
undefined method `[]' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/tunes/tunes_client.rb:59:in `rescue in login_url': 
Could not fetch the login URL from iTunes Connect, the server might be down (RuntimeError)
```

Thanks in advance

Aaron

**Comment by patoroco** [comment]
:+1:  here

**Comment by patoroco** [comment]
+1 here, maybe this version is not updated to last changes on iTunes Connect?

**Comment by Buju77** [comment]
+1 same here, after updating spaceship to 0.14, i'm getting a little different error:

```
/Users/Buju77/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.14.2/lib/spaceship/tunes/tunes_client.rb:100:in `rescue in send_login_request':  (Spaceship::TunesClient::ITunesConnectError)
...
from /Users/Buju77/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.14.2/lib/spaceship/tunes/tunes_client.rb:93:in `send_login_request'
...
```

**Comment by huguesbr** [comment]
+1 fastlane version `1.14.1`

```
[18:13:39]: fastlane finished with errors
[18:13:41]: "\xE2" from ASCII-8BIT to UTF-8
```

**Comment by huguesbr** [comment]
using WatchBuild 0.1.1 work for me today..
